### ISSUE TITLE
PyOpTools inside Freecad loading issue

### ISSUE THREAD

**Issue by biveenslal** [cihologramas/freecad-pyoptools#13] opened 2023-11-03 16:48 UTC
Every time I try to open the pyoptools workbench and try to add a component, I get this error. I tried matching different versions and several ways to fix it. Nothing works. Have you seen this issue before? I hope you can help me with this. Thank you in advance.

Running the Python command 'SphericalLens' failed:
Traceback (most recent call last):
  File "/Users/biveenslal/anaconda3/envs/multipass/Mod/freecad-pyoptools/freecad/pyoptools/pyOpToolsWB/wbcommand.py", line 106, in Activated
    sl = self.gui()
  File "/Users/biveenslal/anaconda3/envs/multipass/Mod/freecad-pyoptools/freecad/pyoptools/pyOpToolsWB/sphericallens.py", line 21, in __init__
    pw = placementWidget()
  File "/Users/biveenslal/anaconda3/envs/multipass/Mod/freecad-pyoptools/freecad/pyoptools/pyOpToolsWB/widgets/placementWidget.py", line 73, in __init__
    self.initUI()
  File "/Users/biveenslal/anaconda3/envs/multipass/Mod/freecad-pyoptools/freecad/pyoptools/pyOpToolsWB/widgets/placementWidget.py", line 78, in initUI
    self.ui = FreeCADGui.PySideUic.loadUi(fn1, self)
  File "<string>", line 4, in <module>

Cannot open file

**Comment by luzpaz** [comment] 2023-11-03 22:32
Please add full about version of FreeCAD and pyoptools version

**Comment by biveenslal** [comment] 2023-11-05 13:17
I am using FreeCAD 0.21.1 and pyoptools 0.2.0. The workbench files are the latest from this repo.  

@ramezquitao

**Comment by luzpaz** [comment] 2023-11-05 13:22
CC @ramezquitao

**Comment by ramezquitao** [comment] 2023-11-05 18:16
I'm sorry I can not provide much help at the moment, because I don't use  pyoptools nor FreeCAD inside Anaconda. However I think the problem is the following: From the error message, it seems FreeCAD is using some Anaconda python installation,  but I guess your pyoptools installation is using a different python interpreter, so can not be found by FreeCAD. 

The way I do it is to install the pyoptools and FreeCAD on the bare system (do not use Anaconda nor AppImage), so they use the system python interpreter. This way I'm sure FreeCAD will see the pyoptools installation. So basically, I'm using Debian but it should work on Mint or Ubuntu, I create a deb package for pyoptools (using make deb) install it, and also use FreeCAD from the repos (installed from deb package), or I compile it directly on my machine.

**Comment by biveenslal** [comment] 2023-11-05 18:20
Hi @ramezquitao,

I am currently using this on a Mac. That's why I had to rely on anaconda to even use pyoptools. Otherwise, I have python compatility issues when installing pyoptools on a bare system. But I will try what you said on a linux machine.

Thank you.

**Comment by ramezquitao** [comment] 2023-11-05 19:10
I have no knowledge and don't know if it is possible, but can´t you try to install pyoptools in the same Anaconda environment as FreeCAD?

**Comment by biveenslal** [comment] 2023-11-08 07:43
I did install pyoptools in the save environment. Sadly it doesn't seem to be working. I can still run it through Jupyter and Pyoptools works fine.

**Comment by ramezquitao** [comment] 2024-01-26 20:57
My local copy was using some links that do not work when installed from the complement manager. It should be fixed now. Please if you have time to check it let me know. I didn't increase the version number, so you need to uninstall and install again.

**Comment by ramezquitao** [comment] 2024-03-06 18:59
I just updated pyOpTools, and right now it is possible to install the FreeCAD-pyOpTools work bench and the pyoptools library to be used with freecad, from the addon manager in FreeCAD 0.2.21. I have tested in Windows, and in Linux. I'm in the process of updating the documentation to reflect this.

**Closed as completed by ramezquitao** 2024-03-06 18:59 UTC
